on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-latest, ubuntu-latest]
        include:
          - os: windows-2019
          - os: macos-latest
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Conan
        run: pip install conan pytest && conan --version
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'
      - name: make build dir
        run: mkdir build && cd build
      - name: install dependecy with conan
        run: conan install .. --settings=build_type=Release --build=missing
      - name: run cmake
        run: cmake ..
      - name: build with cmake
        run: cmake --build . --config Release
      
