name: CMake with Conan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  BUILD_TYPE: Release
  
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Conan
        uses: turtlebrowser/get-conan@v1.2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
      - name: Conan profile update
        run:  |
            conan profile new default --detect
            conan profile update settings.compiler=Visual Studio default
            conan profile update settings.compiler.version=17 default
            conan profile update settings.compiler.cppstd=20 default
            conan profile update settings.build_type=Release default
            conan profile show default

      - name: Conan install dependencies
        run:  |
            mkdir build
            cd build
            conan install . \
            -s build_type=${{env.BUILD_TYPE}} \
            -pr default \
            -b=missing
      - name: run cmake and build
        run: |
          cmake -B ${{github.workspace}}/build
          cmake --build ${{github.workspace}}/build --config Release
      
