name: CMake with Conan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  BUILD_TYPE: Release
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Conan
        run: pip install conan pytest && conan --version
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'
      - name: make build dir
        run: mkdir build && cd build
      - name: Conan profile update
        run:  |
            conan profile new default --detect
            conan profile update settings.compiler=gcc default
            conan profile update settings.compiler.version=10 default
            conan profile update settings.compiler.cppstd=20 default
            conan profile update env.CC=[/usr/bin/gcc-10] default
            conan profile update env.CXX=[/usr/bin/g++-10] default
            conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default
            conan profile show default

      - name: Conan install dependencies
        run:  |
            conan install . \
            -s build_type=${{env.BUILD_TYPE}} \
            --install-folder=${{github.workspace}}/build \
            -pr default \
            -b=missing
      - name: run cmake
        run: cmake -B ${{github.workspace}}/build
      - name: build with cmake
        run: cmake --build ${{github.workspace}}/build --config Release
      
